# Generated by Django 6.0 on 2025-12-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_cliente_funcionario_venda_produto_cod'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='cod_func',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
